add cicd test

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -13,15 +13,12 @@ pipeline
         string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS REGION FOR ECR')
         string(name: 'REPO_DOCKER_USER', defaultValue: 'ribun', description: 'user Docker Hub')
         string(name: 'TAG', defaultValue: 'v1.0', description: 'Tag docker images ex(image:TAG)')
-        choice(name: 'SERVICES', choices: ['auth', 'user', 'task'], description: 'Choice service')
+        // choice(name: 'SERVICES', choices: ['auth', 'user', 'task'], description: 'Choice service')
 
         string(name: 'CLUSTER_NAME', defaultValue: 'muzique-cluster', description: 'Name ECS cluster')
-        string(name: 'SERVICE_NAME', defaultValue: 'web-front-end-muzique', description: 'Name service on ECS')
-        string(name: 'TASK_DEF_NAME', defaultValue: 'task-definition-web-muzique', description: 'Name task definition ECS')
-
-        
+        // string(name: 'SERVICE_NAME', defaultValue: 'web-front-end-muzique-123', description: 'Name service on ECS')
+        // string(name: 'TASK_DEF_NAME', defaultValue: 'task-definition-web-muzique', description: 'Name task definition ECS')
     }
-
     environment {
         AWS_REGION  = "${params.AWS_REGION}"
         SNYK_TOKEN  = credentials('snyk')
@@ -29,19 +26,68 @@ pipeline
         REPO_IMAGE  = "muzique-${params.SERVICES}-service"
 
         CLUSTER_NAME  = "${params.CLUSTER_NAME}"
-        SERVICE_NAME  = "${params.SERVICE_NAME}"
-        TASK_DEF_NAME = "${params.TASK_DEF_NAME}"
-        DIR_NAME = ""
-        PORT =  ""
+    
+        MYSQL_ROOT_PASSWORD = credentials('MYSQL_ROOT_PASSWORD')
+        MYSQL_DATABASE      = "muziquedevops"
+        MYSQL_USER          = "muzique"
+        MYSQL_PASSWORD      = credentials('MYSQL_PASSWORD')
+        MYSQL_HOST          = credentials('MYSQL_HOST')
+        MYSQL_PORT          = "3306"
+        SECRET_KEY          = credentials('SECRET_KEY')
     }
-
     stages {
         stage('Git Checkout') {
             steps {
                 git branch: 'deploy', url: 'https://github.com/minhphuc2544/Muzique-Backend.git'
             }
         }
+        stage('Check services') {
+            script {
+                def changedFiles = sh(script: "git diff --name-only $GIT_PREVIOUS_COMMIT $GIT_COMMIT", returnStdout: true).trim().split("\n")
 
+                def detectServices = ""
+                if (changedFiles.any { it.startsWith("user-service/auth/")}) {
+                    detectServices = "auth"
+                } else if (changedFiles.any { it.startsWith("user-service/user/")}) {
+                    detectServices = "user"
+                } else if (changedFiles.any { it.startsWith("task-service/task")}) {
+                    detectServices = "task"
+                }
+
+                if ( detectServices == "") {
+                    error("Cannot find services need to update!")
+                }
+                env.SERVICES = detectServices
+            }
+        }
+        stage('Setup ENV') {
+            script {
+                def serviceNameMap = [
+                    'auth' : 'auth-service-muzique',
+                    'user' : 'user-service-muzique',
+                    'task' : 'task-service-muzique'
+                ]
+                def taskDefMap = [
+                    'auth' : 'task-definition-auth-muzique',
+                    'user' : 'task-definition-user-muzique',
+                    'task' : 'task-definition-task-muzique'
+                ]
+                def serviceMap = [
+                        'auth' : 'user-service/auth', 
+                        'user' : 'user-service/user',
+                        'task' :  'task-service'
+                ]
+                def portMap = [
+                        'auth' : 8000,
+                        'user' : 8000,
+                        'task' : 8000
+                ]
+                env.SERVICE_NAME = serviceNameMap[env.SERVICES]
+                env.TASK_DEF_NAME = taskDefMap[env.SERVICES]
+                env.DIR_NAME = serviceMap[env.SERVICES]
+                env.PORT = portMap[env.SERVICES]
+            }
+        }
         // stage('Analys code - SonarQube') {
         //     environment {
         //         SCANNER_HOME = tool 'sonar-scanner'
@@ -63,19 +109,24 @@ pipeline
         // }
         // stage('Snyk Test - App (npm)') {
         //     steps {
-        //         sh '''
-        //             snyk auth $SNYK_TOKEN
-        //             snyk test --all-project --severity-threshold=medium --json > ./reports/snyk-report.json || true
-        //         '''
+        //         dir(env.DIR_NAME) {
+        //             sh '''
+        //                 snyk auth $SNYK_TOKEN
+        //                 snyk test --all-project --severity-threshold=medium --json > ./reports/snyk-report.json || true
+        //             '''
+        //         }
         //     }
         // }
         // stage('Snyk Monitor') {
         //     steps {
-        //         sh 'snyk monitor --all-project'
+        //         dir(env.DIR_NAME) {
+        //             sh 'snyk monitor --all-project'
+        //         }
         //     }
         // }
         // stage('OWASP FS SCAN') {
         //     steps {
+        //         dir(env.DIR_NAME) {
         //             dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
         //             dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
         //         }
@@ -83,22 +134,16 @@ pipeline
         // }
         // stage('Trivy FS scan') {
         //     steps {
+        //         dir(env.DIR_NAME) {
         //             sh "trivy fs . > trivyfs.json || true"
+        //         }
         //     }
         // }
         stage('Docker Build'){
             steps {
                 script {
-                    def serviceMap = [
-                        'auth' : 'user-service/auth', 
-                        'user' : 'user-service/user',
-                        'task' :  'task-service'
-                    ]
-                    def DIR_NAME = serviceMap[params.SERVICES]
-
-
-                    withDockerRegistry([credentialsId: 'docker', url: 'https://index.docker.io/v1/']) {  
-                        dir(DIR_NAME) {
+                    withDockerRegistry([credentialsId: 'docker', url: 'https://index.docker.io/v1/']) {
+                        dir(env.DIR_NAME) {
                             sh '''
                                 docker build -t $REPO_IMAGE .
                                 docker tag $REPO_IMAGE $REPO_NAME
@@ -128,14 +173,7 @@ pipeline
         stage('Remove container') {
             steps {
                 script {
-                    def serviceMap = [
-                        'auth' : 'user-service/auth', 
-                        'user' : 'user-service/user',
-                        'task' :  'task-service'
-                    ]
-                    def DIR_NAME = serviceMap[params.SERVICES]
-
-                    dir(DIR_NAME)
+                    dir(env.DIR_NAME)
                     {
                         sh '''
                             docker stop $REPO_IMAGE | true
@@ -148,108 +186,94 @@ pipeline
         stage('Run container') {
             steps {
                 script {
-                    def serviceMap = [
-                        'auth' : 'user-service/auth', 
-                        'user' : 'user-service/user',
-                        'task' :  'task-service'
-                    ]
-                    def DIR_NAME = serviceMap[params.SERVICES]
-
-                    def portMap = [
-                        'auth' : 8000,
-                        'user' : 8000,
-                        'task' : 8000
-                    ]
-                    
-                    def PORT = portMap[params.SERVICES]
-
-                    dir(DIR_NAME)
+                    dir(env.DIR_NAME)
                     {
                         sh """
                             echo "Run contaienr test in jenkins: "
-                            docker run -d --name ${REPO_IMAGE}  -p ${PORT}:8080 "${REPO_NAME}"
+                            docker run -d --name $REPO_IMAGE  -p ${env.PORT}:8080 "$REPO_NAME"
                         """
                     }
                 }
-                
             }
         }
-        // stage('Deploy to DEV') {
-        //     when {
-        //         expression { params.ENVIRONMENT == 'dev' }
-        //     }
-        //     steps {
-        //         withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-key']]) {
-        //             sh '''
-        //                 echo "Deploying to development: "
-        //                 aws ecs describe-task-definition \
-        //                 --task-definition $TASK_DEF_NAME \
-        //                 --query 'taskDefinition' > task-def.json
+        stage('Deploy to DEV') {
+            when {
+                expression { params.ENVIRONMENT == 'dev' }
+            }
+            steps {
+                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-key']]) {
+                    sh """
+                        echo "Deploying to development: "
+                        aws ecs describe-task-definition \
+                        --task-definition ${env.TASK_DEF_NAME} \
+                        --query 'taskDefinition' > task-def.json
 
-        //                 jq --arg img "$REPO_NAME" '
-        //                 {
-        //                     family: .family,
-        //                     networkMode: .networkMode,
-        //                     containerDefinitions: (
-        //                         .containerDefinitions | map(
-        //                             .image = $img
-        //                         )
-        //                     ),
-        //                     requiresCompatibilities: .requiresCompatibilities,
-        //                     cpu: .cpu,
-        //                     memory: .memory,
-        //                     executionRoleArn: .executionRoleArn,
-        //                     taskRoleArn: .taskRoleArn
-        //                 }' task-def.json > new-task-def.json
-                
-        //                 aws ecs update-service \
-        //                     --cluster $CLUSTER_NAME \
-        //                     --service $SERVICE_NAME \
-        //                     --force-new-deployment
-                        
-        //                 echo "Done"
-        //             '''
-        //         }
-        //     }
-        // }
-        // stage('Deploy to PROD') {
-        //     when {
-        //         expression {params.ENVIRONMENT == 'prod'}
-        //     }
-        //     steps {
-        //         withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-key']]) {
-        //             sh '''
-        //                 echo "Deploying to production: "
-        //                 aws ecs describe-task-definition \
-        //                 --task-definition $TASK_DEF_NAME \
-        //                 --query 'taskDefinition' > task-def.json
-                    
+                        # Tạo biến môi trường mới
+                        NEW_ENVS=\"
+                        [
+                            {\\\"name\\\": \\\"MYSQL_ROOT_PASSWORD\\\", \\\"value\\\": \\\"$MYSQL_ROOT_PASSWORD\\\"},
+                            {\\\"name\\\": \\\"MYSQL_DATABASE\\\", \\\"value\\\": \\\"$MYSQL_DATABASE\\\"},
+                            {\\\"name\\\": \\\"MYSQL_USER\\\", \\\"value\\\": \\\"$MYSQL_USER\\\"},
+                            {\\\"name\\\": \\\"MYSQL_PASSWORD\\\", \\\"value\\\": \\\"$MYSQL_PASSWORD\\\"},
+                            {\\\"name\\\": \\\"MYSQL_HOST\\\", \\\"value\\\": \\\"$MYSQL_HOST\\\"},
+                            {\\\"name\\\": \\\"MYSQL_PORT\\\", \\\"value\\\": \\\"$MYSQL_PORT\\\"},
+                            {\\\"name\\\": \\\"SECRET_KEY\\\", \\\"value\\\": \\\"$SECRET_KEY\\\"}
+                        ]
+                        \"
 
-        //                 jq --arg img "$REPO_NAME" '
-        //                 {
-        //                     family: .family,
-        //                     networkMode: .networkMode,
-        //                     containerDefinitions: (
-        //                         .containerDefinitions | map(
-        //                             .image = $img
-        //                         )
-        //                     ),
-        //                     requiresCompatibilities: .requiresCompatibilities,
-        //                     cpu: .cpu,
-        //                     memory: .memory,
-        //                     executionRoleArn: .executionRoleArn,
-        //                     taskRoleArn: .taskRoleArn
-        //                 }' task-def.json > new-task-def.json
-                
-        //                 aws ecs update-service \
-        //                     --cluster $CLUSTER_NAME \
-        //                     --service $SERVICE_NAME \
-        //                     --force-new-deployment
+                        # Tạo file JSON mới bằng jq
+                        cat task-def.json | jq \
+                            --arg IMAGE "$REPO_NAME" \
+                            --arg NAME "$REPO_IMAGE" \
+                            --argjson NEW_ENVS "$NEW_ENVS" \
+                        '
+                        .containerDefinitions |= map(
+                            if .name == $NAME then
+                            .image = $IMAGE
+                            | .environment |= (
+                                reduce $NEW_ENVS[] as $new_var (
+                                    map(if .name == $new_var.name then .value = $new_var.value else . end);
+                                    if any(.name == $new_var.name; true) then . else . + [$new_var] end
+                                )
+                                )
+                            else .
+                            end
+                        )
+                        | {
+                            family,
+                            containerDefinitions,
+                            executionRoleArn,
+                            taskRoleArn,
+                            networkMode,
+                            requiresCompatibilities,
+                            cpu,
+                            memory
+                        }
+                        ' > new-task-def.json
+
+                        # Đăng ký revision mới
+                        aws ecs register-task-definition --cli-input-json file://new-task-def.json > register-task.json
                         
-        //                 echo "Done"
-        //             '''
-        //         }
-        //     }
-        // }
+                        # Update ECS service
+                        NEW_REVISION=$(jq -r '.taskDefinition.revision' register-task.json)
+                        aws ecs update-service --cluster $CLUSTER_NAME --service ${env.SERVICE_NAME} --task-definition ${env.TASK_DEF_NAME}:$NEW_REVISION
+                        
+                        echo "Done"
+                    """
+                }
+            }
+        }
+        stage('Deploy to PROD') {
+            when {
+                expression {params.ENVIRONMENT == 'prod'}
+            }
+            steps {
+                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-key']]) {
+                    sh '''
+                        echo "Deploying to production: "
+                    '''
+                }
+            }
+        }
     }
 }
